"""Pydantic schemas for Agent Chat and Grounded RAG Generation."""

from pydantic import BaseModel, Field


class CitationItem(BaseModel):
    """Citation metadata identifying source context chunk."""

    chunk_id: str = Field(..., description="Unique ID of the source vector chunk")
    filename: str = Field(..., description="Original filename of the document")
    content: str = Field(..., description="Excerpt content from the document")
    similarity_score: float = Field(..., description="Cosine similarity score (0 to 1)")
    chunk_index: int = Field(0, description="Index of chunk within the document")


class ChatRequest(BaseModel):
    """User prompt request for the specialized grounded RAG Agent."""

    query: str = Field(..., min_length=1, max_length=2000, description="Natural language question")
    store: str | None = Field(None, description="Optional target store: 'postgres', 'mongo', or None for auto")
    top_k: int = Field(5, ge=1, le=10, description="Maximum number of context chunks to retrieve")
    score_threshold: float = Field(0.55, ge=0.0, le=1.0, description="Minimum cosine similarity threshold")
    mode: str = Field("precise", description="Query mode: 'precise' for semantic chunks or 'full' for entire raw document knowledge")


class ChatResponse(BaseModel):
    """Strictly grounded answer generated by LLM with cited sources."""

    query: str = Field(..., description="Original user query")
    answer: str = Field(..., description="Synthesized answer strictly based on retrieved knowledge")
    has_grounding: bool = Field(..., description="True if answer is backed by retrieved chunks, False if unknown")
    is_conversational: bool = Field(False, description="True if query was a conversational greeting or pleasantry")
    query_mode: str = Field("precise", description="Query mode executed: 'precise' or 'full'")
    primary_source: str | None = Field(None, description="Filename of the most relevant source document")
    primary_score: float | None = Field(None, description="Similarity percentage of the top matching source")
    citations: list[CitationItem] = Field(default_factory=list, description="Sources used to answer the question")
    total_citations: int = Field(0, description="Count of retrieved chunks above threshold")
    model: str = Field(..., description="LLM model identifier used for generation")
    execution_time_ms: float = Field(..., description="Total execution latency in milliseconds")


